#title in header
title: "Conor Svensson"

#main info
#owner
owner: "A place to capture my thoughts"
#email: 
# info: ""
#description
#desc: "A place to capture my thoughts"

#menu
menu:
  Posts: /archives
  About: /About

#index/main page max show posts (in number)
max_post: 4

# Colors use hex color without #
# Theme color
tcolor: 0FA0CE

# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
usercss: css/user.css

# social profile at the footer/bottom
footer: true
placename: Earth
placelink: https://en.wikipedia.org/wiki/Earth
github: https://github.com/conor10
linkedin: https://linkedin.com/in/conor10
twitter: https://twitter.com/conors10
instagram: https://instagram.com/conors10

# Misc
nanobar: /js/nanobar.min.js
switch_light: ☀️
switch_dark: 🌑

# favicon
favicon: /images/favicon.png
# thumbnail
thumbnail: /images/thumbnail.png

article:
  thumbnail: true

# Google Analytics ID
google_analytics: G-745MX28HDV

# DISQUS comments (sign up to Disqus to get disqus_shortname)
# disqus_enabled: false
# disqus_shortname: https-adisaktijrs-github-io
